chore:: Fix message

diff --git a/.github/actions/sem-title/action.yml b/.github/actions/sem-title/action.yml
--- a/.github/actions/sem-title/action.yml
+++ b/.github/actions/sem-title/action.yml
@@ -41,7 +41,7 @@ runs:
 
         TITLE_HEAD="$(head -n 1 <<< "${TITLE}")"
         PREFIX="$(grep -o -e '^[^:]\+' <<< "${TITLE_HEAD}")" || PREFIX=""
-        if [[ "${PREFIX}" == "" ]]; then echo "::error Missing prefix(type)"; fi
+        if [[ "${PREFIX}" == "" ]]; then echo "::error ::Missing prefix(type)"; fi
 
         TYPE="$(grep -o -e '^[^(!]\+' <<< "${PREFIX}")"
         echo "label(type): ${TYPE}"
@@ -51,7 +51,7 @@ runs:
 
         if [[ ${PREFIX} == *! ]]; then IS_BREAKING_CHANGE="true"; else IS_BREAKING_CHANGE="false"; fi
 
-        validate_type "${TYPE}" || echo ":: invalid type: ${TYPE}"
+        validate_type "${TYPE}" || echo "::error ::invalid type: ${TYPE}"
 
         echo "type=${TYPE}" >> "${GITHUB_OUTPUT}"
         echo "scope=${SCOPE}" >> "${GITHUB_OUTPUT}"
